# https://taskfile.dev
version: '3'


tasks:
  ci:
    desc: Run all tasks required to merge code into the main branch
    cmds:
      - task: ruff:check
      - task: mypy
      - task: pytest

  ruff:check:
    desc: Check linting and formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - uv run ruff check {{.CLI_ARGS}} aoc.py aoc_*
      - uv run ruff format --check {{.CLI_ARGS}} aoc.py aoc_*

  ruff:fix:
    desc: Fix linting errors in Python sources with `astral-sh/ruff`.
    cmds:
      - uv run ruff check --fix {{.CLI_ARGS}} aoc.py aoc_*

  ruff:format:
    desc: Fix formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - uv run ruff format {{.CLI_ARGS}} aoc.py aoc_*

  mypy:
    desc: Check Python type annotations with `python/mypy`.
    cmds:
      - uv run mypy --no-auto-baseline {{.CLI_ARGS}} aoc.py aoc_2024

  pytest:
    desc: Run Python unit tests via `pytest-dev/pytest`
    cmds:
      - uv run pytest {{.CLI_ARGS}} aoc_test.py

  aoc:
    desc: Run the AOC.py script
    cmds:
      - uv run aoc.py {{.CLI_ARGS}}

  aoc:init:
    desc: Run the AOC.py init command
    cmds:
      - uv run aoc.py init {{.CLI_ARGS}}

  aoc:run:
    desc: Run the AOC.py run command
    cmds:
      - uv run aoc.py run {{.CLI_ARGS}}

  aoc:test:
    desc: Run the AOC.py test command
    cmds:
      - uv run aoc.py test {{.CLI_ARGS}}
