# https://taskfile.dev
version: '3'


vars:
  PY_PREFIX:
    sh: if [[ ${PIPENV_ACTIVE:-} != "1" ]]; then echo "pipenv run"; fi


tasks:
  ci:
    desc: Run all tasks required to merge code into the main branch
    cmds:
      - task: ruff:check
      - task: mypy
      - task: pytest

  ruff:check:
    desc: Check linting and formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff check {{.CLI_ARGS}} aoc.py"
      - "{{.PY_PREFIX}} ruff format --check {{.CLI_ARGS}} aoc.py"

  ruff:fix:
    desc: Fix linting errors in Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff check --fix {{.CLI_ARGS}} aoc.py"

  ruff:format:
    desc: Fix formatting of Python sources with `astral-sh/ruff`.
    cmds:
      - "{{.PY_PREFIX}} ruff format {{.CLI_ARGS}} aoc.py"

  mypy:
    desc: Check Python type annotations with `python/mypy`.
    cmds:
      - "{{.PY_PREFIX}} mypy {{.CLI_ARGS}} aoc.py"

  pytest:
    desc: Run Python unit tests via `pytest-dev/pytest`
    cmds:
      - "{{.PY_PREFIX}} pytest {{.CLI_ARGS}} aoc_test.py"
