name: Test Solutions

on: push

jobs:
  test_solutions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Install Dependecies
        working-directory: ./2022
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Test existing solutions
        working-directory: ./2022
        run: pipenv run ./aoc.py -t
